# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/design201807041105.xdc

# IP: ip/ins_mem/ins_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ins_mem || ORIG_REF_NAME==ins_mem} -quiet] -quiet
